#!/usr/bin/env bash

# shellcheck disable=SC2034

# Color configuration for the segments.
# See src/colors/*.bash for the color values
# All segments colors have default values in src/config/colors.conf

# This is how you override them:
# SEGMENTS_TIMESTAMP_COLOR_PRIMARY=$color2
# SEGMENTS_TIMESTAMP_COLOR_SECONDARY=$color5

# Set the path_cwd segment's default colors.
SEGMENTS_PATH_CWD_COLOR_PRIMARY=${SEGMENTS_PATH_CWD_COLOR_PRIMARY:-$color14}
SEGMENTS_PATH_CWD_COLOR_SECONDARY=${SEGMENTS_PATH_CWD_COLOR_SECONDARY:-$color7}
SEGMENTS_PATH_CWD_COLOR_SPLITTER=${SEGMENTS_PATH_CWD_COLOR_SPLITTER:-$color4}

# Set the exit code segment's highlight color to color8 and color4 which is
# typically white on a red background. This is the same as the default color
# scheme for the "command" segment.
SEGMENTS_EXIT_CODE_COLOR_PRIMARY_HIGHLIGHT=${SEGMENTS_EXIT_CODE_COLOR_PRIMARY_HIGHLIGHT:-$color8}
SEGMENTS_EXIT_CODE_COLOR_SECONDARY_HIGHLIGHT=${SEGMENTS_EXIT_CODE_COLOR_SECONDARY_HIGHLIGHT:-$color4}
