#!/bin/bash
# vim: set ft=sh:
#
# Copyright 2025 Ian Lewis
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# enable color support of ls and also add handy aliases
if [ "$(uname)" == "Darwin" ]; then
    export LSCOLORS=ExGxFxDxCxHxHxCbCeEbEb
    export LC_CTYPE=en_US.utf-8
    export LC_ALL=en_US.utf-8
    alias ls='ls -BF'
elif [ "$TERM" != "dumb" ]; then
    eval "$(dircolors -b)"
    alias ls='ls -BF --color=auto'
fi

alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias df='df -h'
alias du='du -h'

# Force ssh to use version 2
alias ssh='ssh -2'

alias scala='scala -deprecation -unchecked -explaintypes -i ~/.import.scala'

# Create a new dev session.
alias ns='tmux-sessionizer'

if [ -f ~/.bash_aliases.local ]; then
    # shellcheck source=/dev/null
    . ~/.bash_aliases.local
fi
