#!/bin/bash
# vim: set ft=sh:

# enable color support of ls and also add handy aliases
if [ `uname` == "Darwin" ]; then
    export LSCOLORS=ExGxFxDxCxHxHxCbCeEbEb
    export LC_CTYPE=en_US.utf-8
    export LC_ALL=en_US.utf-8
    alias ls='ls -BF'
elif [ "$TERM" != "dumb" ]; then
    eval "`dircolors -b`"
    alias ls='ls -BF --color=auto'
fi

alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias df='df -h'
alias du='du -h'

# Force ssh to use version 2
alias ssh='ssh -2'

alias scala='scala -deprecation -unchecked -explaintypes -i ~/.import.scala'

if [ -f ~/.bash_aliases.local ]; then
    . ~/.bash_aliases.local
fi
