#!/usr/bin/env bash
# vim: set ft=sh:
#
# Copyright 2025 Ian Lewis
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function _bash_aliases() {
    # Enable color support for ls
    if [ "$(uname)" == "Darwin" ]; then
        export LSCOLORS=ExGxFxDxCxHxHxCbCeEbEb
        export LC_CTYPE=en_US.utf-8
        export LC_ALL=en_US.utf-8
        alias ls='ls -BF'
    elif [ "$TERM" != "dumb" ]; then
        eval "$(dircolors -b)"
        alias ls='ls -BF --color=auto'
    fi

    alias egrep='egrep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias grep='grep --color=auto'

    # Make rm,cp,mv interactive so you don't accidentally delete files.
    alias rm='rm -i'
    alias cp='cp -i'
    alias mv='mv -i'

    # Make df,du output human readable values by default.
    alias df='df -h'
    alias du='du -h'

    # Force ssh to use version 2
    alias ssh='ssh -2'

    alias scala='scala -deprecation -unchecked -explaintypes -i ~/.import.scala'

    # Create a new dev session.
    alias ns='tmux-sessionizer'

    # Split window and start nvim.
    alias pw='project-windowizer'

    # Load kubectl aliases.
    local bash_lib_dir="${HOME}/.local/share/bash/lib"
    if [ -f "${bash_lib_dir}/kubectl-aliases/.kubectl_aliases" ]; then
        # shellcheck source=/dev/null
        . "${bash_lib_dir}/kubectl-aliases/.kubectl_aliases"
    fi

    if [ -f "${HOME}/.bash_aliases.local" ]; then
        # shellcheck source=/dev/null
        . "${HOME}/.bash_aliases.local"
    fi
}

_bash_aliases
