#!/bin/bash
# vim: set ft=sh:
# Copyright 2024 Ian Lewis
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# pip bash completion start
if command -v python3 >/dev/null 2>&1 && python3 -m pip >/dev/null 2>&1; then
    eval "$(python3 -m pip completion --bash)"
elif command -v python >/dev/null 2>&1 && python -m pip >/dev/null 2>&1; then
    eval "$(python -m pip completion --bash --no-python-version-warning)"
fi

# kubectl bash completion
if command -v kubectl >/dev/null 2>&1; then
    # shellcheck source=/dev/null
    source <(kubectl completion bash)
fi

# Aqua completion
if command -v aqua >/dev/null 2>&1; then
    # shellcheck source=/dev/null
    source <(aqua completion bash)
fi

if [ -f ~/.bash_completion.local ]; then
    # shellcheck source=/dev/null
    . ~/.bash_completion.local
fi
