#!/usr/bin/env bash
# vim: set ft=sh:
#
# Copyright 2025 Ian Lewis
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ~/.bash_logout: executed by bash(1) when login shell exits.

function _bash_logout() {
    # When leaving the console, clear the screen to increase privacy
    if [ "${SHLVL}" = 1 ]; then
        [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
    fi

    if [ -f "${HOME}/.bash_logout.local" ]; then
        # shellcheck source=/dev/null
        source "${HOME}/.bash_logout.local"
    fi
}

_bash_logout
