#!/usr/bin/env bash
# vim: set ft=sh:
#
# Copyright 2025 Ian Lewis
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ~/.profile is typically executed by the command interpreter for interactive
# login shells.
#
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists. However it may be read for other shells so it should be written in
# POSIX-compliant shell script.
#
# See /usr/share/doc/bash/examples/startup-files (bash-doc package) or read
# https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html
# for more information.

# if running bash
if [ -n "${BASH_VERSION}" ]; then
    # include .bashrc if it exists
    if [ -r "${HOME}/.bashrc" ]; then
        # shellcheck source=/dev/null
        source "${HOME}/.bashrc"
    fi
fi

# Local settings
if [ -r "${HOME}/.profile.local" ]; then
    # shellcheck source=/dev/null
    source "${HOME}/.profile.local"
fi
