name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "30 1 * * *"

permissions: {}

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "A friendly reminder that this issue had no activity for 120 days."
          stale-pr-message: "A friendly reminder that this PR had no activity for 120 days."
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          days-before-stale: 120
          days-before-close: 90
          remove-stale-when-updated: true
          exempt-pr-labels: "no-auto-close"
          exempt-issue-labels: "no-auto-close,enhancement,good first issue,help wanted"
          operations-per-run: 1000
          close-issue-label: "auto-closed"
          close-pr-label: "auto-closed"
          close-issue-message: "This issue has been closed due to lack of activity."
          close-pr-message: "This PR has been closed due to lack of activity."
